INI parser
codescalersinternships/RawanMostafa-inigo pull request #1
Opened 2024-09-10 15:05 UTC by RawanMostafa08

https://github.com/codescalersinternships/home/issues/279

2024-09-18 11:13 UTC, AbdelrahmanElawady requested changes
Nice work, Rawan! Left some minor comments

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on .github/workflows/main.yaml
> +on: [push, pull_request]
this causes the workflows to run multiple times which is unnecessary

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on .github/workflows/main.yaml
> +        run: go build -v ./...
No need for build step for a package.

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on .github/workflows/main.yaml
> +        run: go test ./pkg
make the tests in another job with -v

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +var errNotINI = errors.New("this is not an ini file")
errors should be public so package users can check with `errors.Is`

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +}
why is this needed and not have the data directly as `map[string]map[string]string`

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +func InitParser() iniParser {
it's conventionally written as `NewParser`

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +type iniParser struct {
just `Parser`

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +func (i iniParser) populateINI(lines []string) {
you are populating the parser, maybe calling the function `parse` would be better?

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +		if line == "" || strings.HasPrefix(line, ";") {
comments can start with `#`

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +		if strings.Contains(line, "[") && strings.Contains(line, "]") {
This will consider `abc[]` as valid section which is not the case. Instead check for prefix and suffix

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +	map_ map[string]string
why using `_`?

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +//	},
no need to mention that, just what the parser does (parsing INI)

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +			title = strings.TrimSpace(title)
no need to trim spaces inside the brackets

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +			parts := strings.Split(line, "=")
this will cause line like `key=val1=val2=val3` to only parse `key` and `val1` which is not the right. Values can have `=` and you should only split on the firs one.

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +			sec.map_[key] = value
this will panic if global key and values are set. this needs to check whether the key value are in a section or not and return error in case of global keys

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +		return fmt.Errorf("error in reading the file: %v", err)
errors are wrapped with `%w` so they can be unwrapped with `errors.Is`

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +func (i iniParser) LoadFromString(file string) {
I think `data` is more suitable here instead of `file` what do you think?

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +	}
this shouldn't be an error

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +	}
same here

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +	return i.sections[sectionName].map_[key], nil
```suggestion
    val, exists := i.data[section][key]
    return val, exists
```

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +func (i iniParser) Get(sectionName string, key string) (string, error) {
It's not an error if it's not found. You can just return boolean with the string

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +	i.sections[sectionName].map_[key] = value
this shouldn't be an error you should create they section and the key

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +// ToString is a method that returns the parsed ini map of the caller object as one string
`String`

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +	var result string
use strings.Builder if you are concatenating a lot of strings

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +		result += "[" + sectionName + "]\n"
use `fmt.Sprintf` for better readability

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +	sectionNames := make([]string, 0)
you have the number of sections so you can set that when using make like `make([]string, 0, len(i.sections))`

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +		keys := make([]string, 0)
same here

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +			result += key + " = " + i.sections[sectionName].map_[key] + "\n"
use `fmt.Sprintf`

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +		return fmt.Errorf("error in opening the file: %v", err)
use %w

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser_test.go
> +	})
you should cover more cases for malformed sections, global keys, duplicate sections, etc..

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser_test.go
> +		err          string
instead of comparing errors as string, use `error` interface and check with `errors.Is`

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser_test.go
> +			}
```suggestion
			if testcase.err == "" {
				assertEquality(t, expectedFile, parser.sections)
				continue
			}
			assertEquality(t, testcase.err, err.Error())
```

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser_test.go
> +		assertEquality(t, "this parser has no sections", err.Error())
should just return empty slice not an error

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser_test.go
> +	t.Run("Corner case: sections are empty", func(t *testing.T) {
same here

2024-09-18 11:13 UTC, AbdelrahmanElawady commented on pkg/iniparser_test.go
> +	err = parser.SaveToFile(outPath)
make sure to delete the file and use TempDir

2024-09-22 09:41 UTC, RawanMostafa08 commented on .github/workflows/main.yaml
> +on: [push, pull_request]
But I want it to run on pushes and pull requests as well, no?

2024-09-22 09:50 UTC, RawanMostafa08 commented on pkg/iniparser.go
> +}
to be easier to populate and access instead of too much nested maps that may be confusing

2024-09-22 09:51 UTC, AbdelrahmanElawady commented on .github/workflows/main.yaml
> +on: [push, pull_request]
Sure but now all workflows run twice which is not needed

2024-09-22 09:52 UTC, RawanMostafa08 commented on .github/workflows/main.yaml
> +on: [push, pull_request]
So pushes is enough ya3ni?

2024-09-22 09:55 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +}
it's only two nesting, so instead of `map["section"]["key"]` it's now `map["section"].map_["key"]`

2024-09-22 09:56 UTC, AbdelrahmanElawady commented on .github/workflows/main.yaml
> +on: [push, pull_request]
sure

2024-09-22 10:01 UTC, RawanMostafa08 commented on pkg/iniparser.go
> +func (i iniParser) populateINI(lines []string) {
what `parse` function? populateINI is just a private utility that `LoadFromString`  uses

2024-09-22 10:03 UTC, RawanMostafa08 commented on pkg/iniparser.go
> +	map_ map[string]string
because map only is reserved

2024-09-22 10:16 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +	map_ map[string]string
we don't use `_` or snake case in golang

2024-09-22 10:32 UTC, RawanMostafa08 commented on pkg/iniparser.go
> +			sec.map_[key] = value
https://github.com/codescalersinternships/home/issues/21
"assume there're no global keys, every keys need to be part of a section"

2024-09-22 10:38 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +			sec.map_[key] = value
yep it should return an error not panic

2024-09-22 11:04 UTC, AbdelrahmanElawady commented on pkg/iniparser.go
> +func (i iniParser) populateINI(lines []string) {
I meant changing the name from `populateINI` to `parse`

2025-01-13 09:09 UTC, xmonader approved these changes

2025-01-13 09:26 UTC, merged